### ISSUE TITLE
PageSpeed console blank

### ISSUE THREAD

**Issue by eldk** [apache/incubator-pagespeed-mod#1214]
Hello,

With mod_pagespeed 1.10.33.0-7562, url http://domain.tld/pagespeed_admin/console gives a 200 response but nothing is shown.

Other urls from /pagespeed_admin are goods.

Greatings,

Eric

**Comment by oschaaf** [comment]
I can reproduce it. Digging a little bit, manually calling `pagespeed.startConsole()` displays the page correctly. Was that call somehow lost?

**Comment by centminmod** [comment]
i can confirm this happens on ngx_pagespeed 1.10 too

**Comment by jeffkaufman** [comment]
You can also see this not working on http://www.jefftk.com/pagespeed_admin/console

Looking at www.jefftk.com/pagespeed_admin/console?PageSpeedFilters=+debug I don't see `google.setOnLoadCallback(pagespeed.startConsole);` from `pagespeed/system/console_start.js` even though `net/instaweb/instaweb.gyp` contains `'js_includes': [ '<(DEPTH)/pagespeed/system/console_start.js' ],` for both `console_js_dbg` and `console_js_opt`.

@jlporter : any ideas about what might have made the contents of `console_start.js` get dropped?

**Comment by jeffkaufman** [comment]
(I've now verified that this is still broken on trunk; we haven't incidentally fixed it.)

**Comment by jlporter** [comment]
Looks like this was probably broken when I open sourced the closure compiler flow. It should be fixed now by commit a0015d30f802.

**Comment by jmarantz** [comment]
Do we have a unit-test or system-test now that might catch this?  E.g. that
a js symbol exists in the static js file that we serve?

**Comment by jeffkaufman** [comment]
With this change, we're now inlining the call to start it.  You could write a system test for this, but a much more likely regression would be "we're still calling it, but now there's some sort of js error that keeps the console from being displayed".  The right sort of test would be an automated browser test that makes sure there are no js errors and ideally that the console looks right.  But that's a pain (and we don't currently have infrastructure set up for it.)

**Comment by jmarantz** [comment]
We're the call to a JavaScript function that we expect to be in a compiled
external file.  I compiler-configuration problem that dead-code-eliminates
the entire file would cause a simple scan of the file for the expected
symbol to fail.  This seems fairly simple.

**Comment by jeffkaufman** [comment]
I'm still not sure what breakage you're trying to catch.  Are you worried that a future compiler configuration problem would mean that `pagespeed.startConsole` would no longer be defined in our static js?  Or something else?

(The problem with this bug was that `pagespeed.startConsole` was being defined but because of a mistake in how we set up our gyp files it wasn't being called.)

**Comment by crowell** [comment]
there is a test using phantom somewhere. that tests the admin site. It's
not currently part of the checkin suite, but perhaps it should be. (then we
have the downside of requiring phantomjs and casperjs)

On Tue, Mar 8, 2016 at 2:16 PM, Joshua Marantz notifications@github.com
wrote:

> We're the call to a JavaScript function that we expect to be in a compiled
> external file. I compiler-configuration problem that dead-code-eliminates
> the entire file would cause a simple scan of the file for the expected
> symbol to fail. This seems fairly simple.
> 
> On Tue, Mar 8, 2016 at 2:09 PM, Jeff Kaufman notifications@github.com
> wrote:
> 
> > With this change, we're now inlining the call to start it. You could
> > write
> > a system test for this, but a much more likely regression would be "we're
> > still calling it, but now there's some sort of js error that keeps the
> > console from being displayed". The right sort of test would be an
> > automated
> > browser test that makes sure there are no js errors and ideally that the
> > console looks right. But that's a pain (and we don't currently have
> > infrastructure set up for it.)
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/pagespeed/mod_pagespeed/issues/1214#issuecomment-193920742
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pagespeed/mod_pagespeed/issues/1214#issuecomment-193925168
> .

## 

Jeff Crowell
https://github.com/crowell

**Comment by jeffkaufman** [comment]
(A test that checked whether `pagespeed.startConsole` was being defined would have passed, even when this was broken.)

**Comment by jeffkaufman** [comment]
Released in 1.11.33.0.
